fix: use long form of php remi packages for CentOS 7 as its php-* symlink does not seem to be working
as per https://github.com/JonasPammer/ansible-role-mediawiki/actions/runs/3081298318/jobs/4979682174#step:8:799

```
      Error: Package: php-bcmath-5.4.16-48.el7.x86_64 (base)
                 Requires: php-common(x86-64) = 5.4.16-48.el7
                 Installed: php-common-7.4.30-1.el7.remi.x86_64 (@remi-php74)
                     php-common(x86-64) = 7.4.30-1.el7.remi
                 Available: php-common-5.4.16-48.el7.x86_64 (base)
                     php-common(x86-64) = 5.4.16-48.el7
      Error: Package: php-intl-5.4.16-48.el7.x86_64 (base)
                 Requires: php-common(x86-64) = 5.4.16-48.el7
                 Installed: php-common-7.4.30-1.el7.remi.x86_64 (@remi-php74)
                     php-common(x86-64) = 7.4.30-1.el7.remi
                 Available: php-common-5.4.16-48.el7.x86_64 (base)
                     php-common(x86-64) = 5.4.16-48.el7
```